(* This file is generated by ortac qcheck-stm,
   edit how you run the tool instead *)
[@@@ocaml.warning "-26-27-69-32"]
open Array
module Ortac_runtime = Ortac_runtime_qcheck_stm
module SUT =
  (Ortac_runtime.SUT.Make)(struct
                             type sut = char t
                             let init = Some (fun () -> make 16 'a')
                           end)
module ModelElt =
  struct
    type nonrec elt = {
      size: int ;
      contents: char list }
    let init =
      Some
        (let i_4 = 16
         and a_5 = 'a' in
         {
           size =
             (try i_4
              with
              | e ->
                  raise
                    (Ortac_runtime.Partial_function
                       (e,
                         {
                           Ortac_runtime.start =
                             {
                               pos_fname = "array.mli";
                               pos_lnum = 23;
                               pos_bol = 948;
                               pos_cnum = 969
                             };
                           Ortac_runtime.stop =
                             {
                               pos_fname = "array.mli";
                               pos_lnum = 23;
                               pos_bol = 948;
                               pos_cnum = 970
                             }
                         })));
           contents =
             (try
                Ortac_runtime.Gospelstdlib.List.init
                  (Ortac_runtime.Gospelstdlib.integer_of_int i_4)
                  (fun j_2 -> a_5)
              with
              | e ->
                  raise
                    (Ortac_runtime.Partial_function
                       (e,
                         {
                           Ortac_runtime.start =
                             {
                               pos_fname = "array.mli";
                               pos_lnum = 24;
                               pos_bol = 971;
                               pos_cnum = 996
                             };
                           Ortac_runtime.stop =
                             {
                               pos_fname = "array.mli";
                               pos_lnum = 24;
                               pos_bol = 971;
                               pos_cnum = 1020
                             }
                         })))
         })
  end
module Model = (Ortac_runtime.Model.Make)(ModelElt)
module Spec =
  struct
    open STM
    module QCheck =
      struct
        include QCheck
        module Gen = struct include Gen
                            let int = small_signed_int end
      end
    type _ ty +=  
      | Integer: Ortac_runtime.integer ty 
    let integer = (Integer, Ortac_runtime.string_of_integer)
    type sut = SUT.t
    let init_sut = SUT.create
    type state = Model.t
    let init_state = Model.create ()
    type cmd =
      | Length 
      | Get of int 
      | Set of int * char 
      | Fill of int * int * char 
      | To_list 
      | Mem of char 
    let show_cmd cmd__001_ =
      match cmd__001_ with
      | Length -> Format.asprintf "%s sut" "length"
      | Get i ->
          Format.asprintf "protect (fun () -> %s sut %a)" "get"
            (Util.Pp.pp_int true) i
      | Set (i_1, a_1) ->
          Format.asprintf "protect (fun () -> %s sut %a %a)" "set"
            (Util.Pp.pp_int true) i_1 (Util.Pp.pp_char true) a_1
      | Fill (i_2, j, a_2) ->
          Format.asprintf "protect (fun () -> %s sut %a %a %a)" "fill"
            (Util.Pp.pp_int true) i_2 (Util.Pp.pp_int true) j
            (Util.Pp.pp_char true) a_2
      | To_list -> Format.asprintf "%s sut" "to_list"
      | Mem a_3 ->
          Format.asprintf "%s %a sut" "mem" (Util.Pp.pp_char true) a_3
    let cleanup _ = ()
    let arb_cmd _ =
      let open QCheck in
        make ~print:show_cmd
          (let open Gen in
             oneof
               [pure Length;
               (pure (fun i -> Get i)) <*> int;
               ((pure (fun i_1 -> fun a_1 -> Set (i_1, a_1))) <*> int) <*>
                 char;
               (((pure (fun i_2 -> fun j -> fun a_2 -> Fill (i_2, j, a_2)))
                   <*> int)
                  <*> int)
                 <*> char;
               pure To_list;
               (pure (fun a_3 -> Mem a_3)) <*> char])
    let next_state cmd__002_ state__003_ =
      match cmd__002_ with
      | Length -> state__003_
      | Get i -> state__003_
      | Set (i_1, a_1) ->
          let tmp__006_ = Model.get state__003_ 0 in
          if
            (try
               let __t1__007_ =
                 Ortac_runtime.Gospelstdlib.(<=)
                   (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                   (Ortac_runtime.Gospelstdlib.integer_of_int i_1) in
               let __t2__008_ =
                 Ortac_runtime.Gospelstdlib.(<)
                   (Ortac_runtime.Gospelstdlib.integer_of_int i_1)
                   (Ortac_runtime.Gospelstdlib.integer_of_int tmp__006_.size) in
               __t1__007_ && __t2__008_
             with
             | e ->
                 raise
                   (Ortac_runtime.Partial_function
                      (e,
                        {
                          Ortac_runtime.start =
                            {
                              pos_fname = "array.mli";
                              pos_lnum = 16;
                              pos_bol = 582;
                              pos_cnum = 593
                            };
                          Ortac_runtime.stop =
                            {
                              pos_fname = "array.mli";
                              pos_lnum = 16;
                              pos_bol = 582;
                              pos_cnum = 608
                            }
                        })))
          then
            Model.push (Model.drop_n state__003_ 1)
              {
                tmp__006_ with
                contents =
                  (try
                     Ortac_runtime.Gospelstdlib.List.mapi
                       (fun j_1 ->
                          fun x ->
                            if
                              j_1 =
                                (Ortac_runtime.Gospelstdlib.integer_of_int
                                   i_1)
                            then a_1
                            else x) tmp__006_.contents
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 18;
                                    pos_bol = 633;
                                    pos_cnum = 658
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 18;
                                    pos_bol = 633;
                                    pos_cnum = 732
                                  }
                              })))
              }
          else state__003_
      | Fill (i_2, j, a_2) ->
          let tmp__009_ = Model.get state__003_ 0 in
          if
            (try
               Ortac_runtime.Gospelstdlib.(<=)
                 (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                 (Ortac_runtime.Gospelstdlib.integer_of_int i_2)
             with
             | e ->
                 raise
                   (Ortac_runtime.Partial_function
                      (e,
                        {
                          Ortac_runtime.start =
                            {
                              pos_fname = "array.mli";
                              pos_lnum = 28;
                              pos_bol = 1183;
                              pos_cnum = 1194
                            };
                          Ortac_runtime.stop =
                            {
                              pos_fname = "array.mli";
                              pos_lnum = 28;
                              pos_bol = 1183;
                              pos_cnum = 1200
                            }
                        })))
              &&
              ((try
                  Ortac_runtime.Gospelstdlib.(<=)
                    (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                    (Ortac_runtime.Gospelstdlib.integer_of_int j)
                with
                | e ->
                    raise
                      (Ortac_runtime.Partial_function
                         (e,
                           {
                             Ortac_runtime.start =
                               {
                                 pos_fname = "array.mli";
                                 pos_lnum = 29;
                                 pos_bol = 1201;
                                 pos_cnum = 1212
                               };
                             Ortac_runtime.stop =
                               {
                                 pos_fname = "array.mli";
                                 pos_lnum = 29;
                                 pos_bol = 1201;
                                 pos_cnum = 1218
                               }
                           })))
                 &&
                 ((try
                     Ortac_runtime.Gospelstdlib.(<=)
                       (Ortac_runtime.Gospelstdlib.(+)
                          (Ortac_runtime.Gospelstdlib.integer_of_int i_2)
                          (Ortac_runtime.Gospelstdlib.integer_of_int j))
                       (Ortac_runtime.Gospelstdlib.integer_of_int
                          tmp__009_.size)
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 30;
                                    pos_bol = 1219;
                                    pos_cnum = 1230
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 30;
                                    pos_bol = 1219;
                                    pos_cnum = 1245
                                  }
                              })))))
          then
            Model.push (Model.drop_n state__003_ 1)
              {
                tmp__009_ with
                contents =
                  (try
                     Ortac_runtime.Gospelstdlib.List.mapi
                       (fun k ->
                          fun x_1 ->
                            if
                              let __t1__010_ =
                                Ortac_runtime.Gospelstdlib.(<=)
                                  (Ortac_runtime.Gospelstdlib.integer_of_int
                                     i_2) k in
                              let __t2__011_ =
                                Ortac_runtime.Gospelstdlib.(<) k
                                  (Ortac_runtime.Gospelstdlib.(+)
                                     (Ortac_runtime.Gospelstdlib.integer_of_int
                                        i_2)
                                     (Ortac_runtime.Gospelstdlib.integer_of_int
                                        j)) in
                              __t1__010_ && __t2__011_
                            then a_2
                            else x_1) tmp__009_.contents
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 32;
                                    pos_bol = 1270;
                                    pos_cnum = 1295
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 32;
                                    pos_bol = 1270;
                                    pos_cnum = 1364
                                  }
                              })))
              }
          else state__003_
      | To_list -> state__003_
      | Mem a_3 -> state__003_
    let precond cmd__042_ state__043_ =
      match cmd__042_ with
      | Length -> true
      | Get i -> true
      | Set (i_1, a_1) -> true
      | Fill (i_2, j, a_2) -> true
      | To_list -> true
      | Mem a_3 -> true
    let postcond _ _ _ = true
    let run cmd__044_ sut__045_ =
      match cmd__044_ with
      | Length ->
          Res
            (int,
              (let tmp__046_ = SUT.pop sut__045_ in
               let res__047_ = length tmp__046_ in
               (SUT.push tmp__046_ sut__045_; res__047_)))
      | Get i ->
          Res
            ((result char exn),
              (let tmp__048_ = SUT.pop sut__045_ in
               let res__049_ = protect (fun () -> get tmp__048_ i) () in
               (SUT.push tmp__048_ sut__045_; res__049_)))
      | Set (i_1, a_1) ->
          Res
            ((result unit exn),
              (let tmp__050_ = SUT.pop sut__045_ in
               let res__051_ = protect (fun () -> set tmp__050_ i_1 a_1) () in
               (SUT.push tmp__050_ sut__045_; res__051_)))
      | Fill (i_2, j, a_2) ->
          Res
            ((result unit exn),
              (let tmp__052_ = SUT.pop sut__045_ in
               let res__053_ =
                 protect (fun () -> fill tmp__052_ i_2 j a_2) () in
               (SUT.push tmp__052_ sut__045_; res__053_)))
      | To_list ->
          Res
            ((list char),
              (let tmp__054_ = SUT.pop sut__045_ in
               let res__055_ = to_list tmp__054_ in
               (SUT.push tmp__054_ sut__045_; res__055_)))
      | Mem a_3 ->
          Res
            (bool,
              (let tmp__056_ = SUT.pop sut__045_ in
               let res__057_ = mem a_3 tmp__056_ in
               (SUT.push tmp__056_ sut__045_; res__057_)))
  end
module STMTests = (Ortac_runtime.Make)(Spec)
let check_init_state () = ()
let ortac_postcond cmd__014_ state__015_ res__016_ =
  let open Spec in
    let open STM in
      let new_state__017_ = lazy (next_state cmd__014_ state__015_) in
      match (cmd__014_, res__016_) with
      | (Length, Res ((Int, _), i_3)) ->
          if
            let t_new__021_ = lazy (Model.get (Lazy.force new_state__017_) 0) in
            let t_old__020_ = lazy (Model.get state__015_ 0) in
            (try i_3 = (Lazy.force t_new__021_).size
             with
             | e ->
                 raise
                   (Ortac_runtime.Partial_function
                      (e,
                        {
                          Ortac_runtime.start =
                            {
                              pos_fname = "array.mli";
                              pos_lnum = 7;
                              pos_bol = 238;
                              pos_cnum = 250
                            };
                          Ortac_runtime.stop =
                            {
                              pos_fname = "array.mli";
                              pos_lnum = 7;
                              pos_bol = 238;
                              pos_cnum = 260
                            }
                        })))
          then None
          else
            Some
              (Ortac_runtime.report "Array" "make 16 'a'"
                 (Either.right
                    (Res
                       (int,
                         (let t_new__019_ =
                            lazy (Model.get (Lazy.force new_state__017_) 0) in
                          let t_old__018_ = lazy (Model.get state__015_ 0) in
                          try (Lazy.force t_new__019_).size
                          with
                          | e ->
                              raise
                                (Ortac_runtime.Partial_function
                                   (e,
                                     {
                                       Ortac_runtime.start =
                                         {
                                           pos_fname = "array.mli";
                                           pos_lnum = 7;
                                           pos_bol = 238;
                                           pos_cnum = 254
                                         };
                                       Ortac_runtime.stop =
                                         {
                                           pos_fname = "array.mli";
                                           pos_lnum = 7;
                                           pos_bol = 238;
                                           pos_cnum = 260
                                         }
                                     })))))) "length"
                 [("i = t.size",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "array.mli";
                          pos_lnum = 7;
                          pos_bol = 238;
                          pos_cnum = 250
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "array.mli";
                          pos_lnum = 7;
                          pos_bol = 238;
                          pos_cnum = 260
                        }
                    })])
      | (Get i, Res ((Result (Char, Exn), _), a_4)) ->
          (match if
                   let tmp__027_ = Model.get state__015_ 0 in
                   try
                     let __t1__028_ =
                       Ortac_runtime.Gospelstdlib.(<=)
                         (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                         (Ortac_runtime.Gospelstdlib.integer_of_int i) in
                     let __t2__029_ =
                       Ortac_runtime.Gospelstdlib.(<)
                         (Ortac_runtime.Gospelstdlib.integer_of_int i)
                         (Ortac_runtime.Gospelstdlib.integer_of_int
                            tmp__027_.size) in
                     __t1__028_ && __t2__029_
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 11;
                                    pos_bol = 378;
                                    pos_cnum = 389
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 11;
                                    pos_bol = 378;
                                    pos_cnum = 404
                                  }
                              }))
                 then None
                 else
                   Some
                     (Ortac_runtime.report "Array" "make 16 'a'"
                        (Either.left "Invalid_argument") "get"
                        [("0 <= i < t.size",
                           {
                             Ortac_runtime.start =
                               {
                                 pos_fname = "array.mli";
                                 pos_lnum = 11;
                                 pos_bol = 378;
                                 pos_cnum = 389
                               };
                             Ortac_runtime.stop =
                               {
                                 pos_fname = "array.mli";
                                 pos_lnum = 11;
                                 pos_bol = 378;
                                 pos_cnum = 404
                               }
                           })])
           with
           | None ->
               (match a_4 with
                | Ok a_4 ->
                    if
                      let t_new__026_ =
                        lazy (Model.get (Lazy.force new_state__017_) 0) in
                      let t_old__025_ = lazy (Model.get state__015_ 0) in
                      (try
                         a_4 =
                           (Ortac_runtime.Gospelstdlib.List.nth
                              (Lazy.force t_new__026_).contents
                              (Ortac_runtime.Gospelstdlib.integer_of_int i))
                       with
                       | e ->
                           raise
                             (Ortac_runtime.Partial_function
                                (e,
                                  {
                                    Ortac_runtime.start =
                                      {
                                        pos_fname = "array.mli";
                                        pos_lnum = 12;
                                        pos_bol = 405;
                                        pos_cnum = 417
                                      };
                                    Ortac_runtime.stop =
                                      {
                                        pos_fname = "array.mli";
                                        pos_lnum = 12;
                                        pos_bol = 405;
                                        pos_cnum = 442
                                      }
                                  })))
                    then None
                    else
                      Some
                        (Ortac_runtime.report "Array" "make 16 'a'"
                           (Either.right
                              (Res
                                 (char,
                                   (let t_new__024_ =
                                      lazy
                                        (Model.get
                                           (Lazy.force new_state__017_) 0) in
                                    let t_old__023_ =
                                      lazy (Model.get state__015_ 0) in
                                    try
                                      Ortac_runtime.Gospelstdlib.List.nth
                                        (Lazy.force t_new__024_).contents
                                        (Ortac_runtime.Gospelstdlib.integer_of_int
                                           i)
                                    with
                                    | e ->
                                        raise
                                          (Ortac_runtime.Partial_function
                                             (e,
                                               {
                                                 Ortac_runtime.start =
                                                   {
                                                     pos_fname = "array.mli";
                                                     pos_lnum = 12;
                                                     pos_bol = 405;
                                                     pos_cnum = 421
                                                   };
                                                 Ortac_runtime.stop =
                                                   {
                                                     pos_fname = "array.mli";
                                                     pos_lnum = 12;
                                                     pos_bol = 405;
                                                     pos_cnum = 442
                                                   }
                                               })))))) "get"
                           [("a = List.nth t.contents i",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 12;
                                    pos_bol = 405;
                                    pos_cnum = 417
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 12;
                                    pos_bol = 405;
                                    pos_cnum = 442
                                  }
                              })])
                | _ -> None)
           | _ ->
               (match a_4 with
                | Error (Invalid_argument _) -> None
                | _ ->
                    if
                      let tmp__027_ = Model.get state__015_ 0 in
                      (try
                         let __t1__028_ =
                           Ortac_runtime.Gospelstdlib.(<=)
                             (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                             (Ortac_runtime.Gospelstdlib.integer_of_int i) in
                         let __t2__029_ =
                           Ortac_runtime.Gospelstdlib.(<)
                             (Ortac_runtime.Gospelstdlib.integer_of_int i)
                             (Ortac_runtime.Gospelstdlib.integer_of_int
                                tmp__027_.size) in
                         __t1__028_ && __t2__029_
                       with
                       | e ->
                           raise
                             (Ortac_runtime.Partial_function
                                (e,
                                  {
                                    Ortac_runtime.start =
                                      {
                                        pos_fname = "array.mli";
                                        pos_lnum = 11;
                                        pos_bol = 378;
                                        pos_cnum = 389
                                      };
                                    Ortac_runtime.stop =
                                      {
                                        pos_fname = "array.mli";
                                        pos_lnum = 11;
                                        pos_bol = 378;
                                        pos_cnum = 404
                                      }
                                  })))
                    then None
                    else
                      Some
                        (Ortac_runtime.report "Array" "make 16 'a'"
                           (Either.left "Invalid_argument") "get"
                           [("0 <= i < t.size",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 11;
                                    pos_bol = 378;
                                    pos_cnum = 389
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 11;
                                    pos_bol = 378;
                                    pos_cnum = 404
                                  }
                              })])))
      | (Set (i_1, a_1), Res ((Result (Unit, Exn), _), res)) ->
          (match if
                   let tmp__030_ = Model.get state__015_ 0 in
                   try
                     let __t1__031_ =
                       Ortac_runtime.Gospelstdlib.(<=)
                         (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                         (Ortac_runtime.Gospelstdlib.integer_of_int i_1) in
                     let __t2__032_ =
                       Ortac_runtime.Gospelstdlib.(<)
                         (Ortac_runtime.Gospelstdlib.integer_of_int i_1)
                         (Ortac_runtime.Gospelstdlib.integer_of_int
                            tmp__030_.size) in
                     __t1__031_ && __t2__032_
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 16;
                                    pos_bol = 582;
                                    pos_cnum = 593
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 16;
                                    pos_bol = 582;
                                    pos_cnum = 608
                                  }
                              }))
                 then None
                 else
                   Some
                     (Ortac_runtime.report "Array" "make 16 'a'"
                        (Either.left "Invalid_argument") "set"
                        [("0 <= i < t.size",
                           {
                             Ortac_runtime.start =
                               {
                                 pos_fname = "array.mli";
                                 pos_lnum = 16;
                                 pos_bol = 582;
                                 pos_cnum = 593
                               };
                             Ortac_runtime.stop =
                               {
                                 pos_fname = "array.mli";
                                 pos_lnum = 16;
                                 pos_bol = 582;
                                 pos_cnum = 608
                               }
                           })])
           with
           | None -> (match res with | Ok _ -> None | _ -> None)
           | _ ->
               (match res with
                | Error (Invalid_argument _) -> None
                | _ ->
                    if
                      let tmp__030_ = Model.get state__015_ 0 in
                      (try
                         let __t1__031_ =
                           Ortac_runtime.Gospelstdlib.(<=)
                             (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                             (Ortac_runtime.Gospelstdlib.integer_of_int i_1) in
                         let __t2__032_ =
                           Ortac_runtime.Gospelstdlib.(<)
                             (Ortac_runtime.Gospelstdlib.integer_of_int i_1)
                             (Ortac_runtime.Gospelstdlib.integer_of_int
                                tmp__030_.size) in
                         __t1__031_ && __t2__032_
                       with
                       | e ->
                           raise
                             (Ortac_runtime.Partial_function
                                (e,
                                  {
                                    Ortac_runtime.start =
                                      {
                                        pos_fname = "array.mli";
                                        pos_lnum = 16;
                                        pos_bol = 582;
                                        pos_cnum = 593
                                      };
                                    Ortac_runtime.stop =
                                      {
                                        pos_fname = "array.mli";
                                        pos_lnum = 16;
                                        pos_bol = 582;
                                        pos_cnum = 608
                                      }
                                  })))
                    then None
                    else
                      Some
                        (Ortac_runtime.report "Array" "make 16 'a'"
                           (Either.left "Invalid_argument") "set"
                           [("0 <= i < t.size",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 16;
                                    pos_bol = 582;
                                    pos_cnum = 593
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 16;
                                    pos_bol = 582;
                                    pos_cnum = 608
                                  }
                              })])))
      | (Fill (i_2, j, a_2), Res ((Result (Unit, Exn), _), res)) ->
          (match Ortac_runtime.append
                   (if
                      let tmp__033_ = Model.get state__015_ 0 in
                      try
                        Ortac_runtime.Gospelstdlib.(<=)
                          (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                          (Ortac_runtime.Gospelstdlib.integer_of_int i_2)
                      with
                      | e ->
                          raise
                            (Ortac_runtime.Partial_function
                               (e,
                                 {
                                   Ortac_runtime.start =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 28;
                                       pos_bol = 1183;
                                       pos_cnum = 1194
                                     };
                                   Ortac_runtime.stop =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 28;
                                       pos_bol = 1183;
                                       pos_cnum = 1200
                                     }
                                 }))
                    then None
                    else
                      Some
                        (Ortac_runtime.report "Array" "make 16 'a'"
                           (Either.left "Invalid_argument") "fill"
                           [("0 <= i",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 28;
                                    pos_bol = 1183;
                                    pos_cnum = 1194
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "array.mli";
                                    pos_lnum = 28;
                                    pos_bol = 1183;
                                    pos_cnum = 1200
                                  }
                              })]))
                   (Ortac_runtime.append
                      (if
                         let tmp__033_ = Model.get state__015_ 0 in
                         try
                           Ortac_runtime.Gospelstdlib.(<=)
                             (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                             (Ortac_runtime.Gospelstdlib.integer_of_int j)
                         with
                         | e ->
                             raise
                               (Ortac_runtime.Partial_function
                                  (e,
                                    {
                                      Ortac_runtime.start =
                                        {
                                          pos_fname = "array.mli";
                                          pos_lnum = 29;
                                          pos_bol = 1201;
                                          pos_cnum = 1212
                                        };
                                      Ortac_runtime.stop =
                                        {
                                          pos_fname = "array.mli";
                                          pos_lnum = 29;
                                          pos_bol = 1201;
                                          pos_cnum = 1218
                                        }
                                    }))
                       then None
                       else
                         Some
                           (Ortac_runtime.report "Array" "make 16 'a'"
                              (Either.left "Invalid_argument") "fill"
                              [("0 <= j",
                                 {
                                   Ortac_runtime.start =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 29;
                                       pos_bol = 1201;
                                       pos_cnum = 1212
                                     };
                                   Ortac_runtime.stop =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 29;
                                       pos_bol = 1201;
                                       pos_cnum = 1218
                                     }
                                 })]))
                      (if
                         let tmp__033_ = Model.get state__015_ 0 in
                         try
                           Ortac_runtime.Gospelstdlib.(<=)
                             (Ortac_runtime.Gospelstdlib.(+)
                                (Ortac_runtime.Gospelstdlib.integer_of_int
                                   i_2)
                                (Ortac_runtime.Gospelstdlib.integer_of_int j))
                             (Ortac_runtime.Gospelstdlib.integer_of_int
                                tmp__033_.size)
                         with
                         | e ->
                             raise
                               (Ortac_runtime.Partial_function
                                  (e,
                                    {
                                      Ortac_runtime.start =
                                        {
                                          pos_fname = "array.mli";
                                          pos_lnum = 30;
                                          pos_bol = 1219;
                                          pos_cnum = 1230
                                        };
                                      Ortac_runtime.stop =
                                        {
                                          pos_fname = "array.mli";
                                          pos_lnum = 30;
                                          pos_bol = 1219;
                                          pos_cnum = 1245
                                        }
                                    }))
                       then None
                       else
                         Some
                           (Ortac_runtime.report "Array" "make 16 'a'"
                              (Either.left "Invalid_argument") "fill"
                              [("i + j <= t.size",
                                 {
                                   Ortac_runtime.start =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 30;
                                       pos_bol = 1219;
                                       pos_cnum = 1230
                                     };
                                   Ortac_runtime.stop =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 30;
                                       pos_bol = 1219;
                                       pos_cnum = 1245
                                     }
                                 })])))
           with
           | None -> (match res with | Ok _ -> None | _ -> None)
           | _ ->
               (match res with
                | Error (Invalid_argument _) -> None
                | _ ->
                    Ortac_runtime.append
                      (if
                         let tmp__033_ = Model.get state__015_ 0 in
                         try
                           Ortac_runtime.Gospelstdlib.(<=)
                             (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                             (Ortac_runtime.Gospelstdlib.integer_of_int i_2)
                         with
                         | e ->
                             raise
                               (Ortac_runtime.Partial_function
                                  (e,
                                    {
                                      Ortac_runtime.start =
                                        {
                                          pos_fname = "array.mli";
                                          pos_lnum = 28;
                                          pos_bol = 1183;
                                          pos_cnum = 1194
                                        };
                                      Ortac_runtime.stop =
                                        {
                                          pos_fname = "array.mli";
                                          pos_lnum = 28;
                                          pos_bol = 1183;
                                          pos_cnum = 1200
                                        }
                                    }))
                       then None
                       else
                         Some
                           (Ortac_runtime.report "Array" "make 16 'a'"
                              (Either.left "Invalid_argument") "fill"
                              [("0 <= i",
                                 {
                                   Ortac_runtime.start =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 28;
                                       pos_bol = 1183;
                                       pos_cnum = 1194
                                     };
                                   Ortac_runtime.stop =
                                     {
                                       pos_fname = "array.mli";
                                       pos_lnum = 28;
                                       pos_bol = 1183;
                                       pos_cnum = 1200
                                     }
                                 })]))
                      (Ortac_runtime.append
                         (if
                            let tmp__033_ = Model.get state__015_ 0 in
                            try
                              Ortac_runtime.Gospelstdlib.(<=)
                                (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                                (Ortac_runtime.Gospelstdlib.integer_of_int j)
                            with
                            | e ->
                                raise
                                  (Ortac_runtime.Partial_function
                                     (e,
                                       {
                                         Ortac_runtime.start =
                                           {
                                             pos_fname = "array.mli";
                                             pos_lnum = 29;
                                             pos_bol = 1201;
                                             pos_cnum = 1212
                                           };
                                         Ortac_runtime.stop =
                                           {
                                             pos_fname = "array.mli";
                                             pos_lnum = 29;
                                             pos_bol = 1201;
                                             pos_cnum = 1218
                                           }
                                       }))
                          then None
                          else
                            Some
                              (Ortac_runtime.report "Array" "make 16 'a'"
                                 (Either.left "Invalid_argument") "fill"
                                 [("0 <= j",
                                    {
                                      Ortac_runtime.start =
                                        {
                                          pos_fname = "array.mli";
                                          pos_lnum = 29;
                                          pos_bol = 1201;
                                          pos_cnum = 1212
                                        };
                                      Ortac_runtime.stop =
                                        {
                                          pos_fname = "array.mli";
                                          pos_lnum = 29;
                                          pos_bol = 1201;
                                          pos_cnum = 1218
                                        }
                                    })]))
                         (if
                            let tmp__033_ = Model.get state__015_ 0 in
                            try
                              Ortac_runtime.Gospelstdlib.(<=)
                                (Ortac_runtime.Gospelstdlib.(+)
                                   (Ortac_runtime.Gospelstdlib.integer_of_int
                                      i_2)
                                   (Ortac_runtime.Gospelstdlib.integer_of_int
                                      j))
                                (Ortac_runtime.Gospelstdlib.integer_of_int
                                   tmp__033_.size)
                            with
                            | e ->
                                raise
                                  (Ortac_runtime.Partial_function
                                     (e,
                                       {
                                         Ortac_runtime.start =
                                           {
                                             pos_fname = "array.mli";
                                             pos_lnum = 30;
                                             pos_bol = 1219;
                                             pos_cnum = 1230
                                           };
                                         Ortac_runtime.stop =
                                           {
                                             pos_fname = "array.mli";
                                             pos_lnum = 30;
                                             pos_bol = 1219;
                                             pos_cnum = 1245
                                           }
                                       }))
                          then None
                          else
                            Some
                              (Ortac_runtime.report "Array" "make 16 'a'"
                                 (Either.left "Invalid_argument") "fill"
                                 [("i + j <= t.size",
                                    {
                                      Ortac_runtime.start =
                                        {
                                          pos_fname = "array.mli";
                                          pos_lnum = 30;
                                          pos_bol = 1219;
                                          pos_cnum = 1230
                                        };
                                      Ortac_runtime.stop =
                                        {
                                          pos_fname = "array.mli";
                                          pos_lnum = 30;
                                          pos_bol = 1219;
                                          pos_cnum = 1245
                                        }
                                    })])))))
      | (To_list, Res ((List (Char), _), l)) ->
          if
            let t_new__037_ = lazy (Model.get (Lazy.force new_state__017_) 0) in
            let t_old__036_ = lazy (Model.get state__015_ 0) in
            (try l = (Lazy.force t_new__037_).contents
             with
             | e ->
                 raise
                   (Ortac_runtime.Partial_function
                      (e,
                        {
                          Ortac_runtime.start =
                            {
                              pos_fname = "array.mli";
                              pos_lnum = 36;
                              pos_bol = 1559;
                              pos_cnum = 1571
                            };
                          Ortac_runtime.stop =
                            {
                              pos_fname = "array.mli";
                              pos_lnum = 36;
                              pos_bol = 1559;
                              pos_cnum = 1585
                            }
                        })))
          then None
          else
            Some
              (Ortac_runtime.report "Array" "make 16 'a'"
                 (Either.right
                    (Res
                       ((list char),
                         (let t_new__035_ =
                            lazy (Model.get (Lazy.force new_state__017_) 0) in
                          let t_old__034_ = lazy (Model.get state__015_ 0) in
                          try (Lazy.force t_new__035_).contents
                          with
                          | e ->
                              raise
                                (Ortac_runtime.Partial_function
                                   (e,
                                     {
                                       Ortac_runtime.start =
                                         {
                                           pos_fname = "array.mli";
                                           pos_lnum = 36;
                                           pos_bol = 1559;
                                           pos_cnum = 1575
                                         };
                                       Ortac_runtime.stop =
                                         {
                                           pos_fname = "array.mli";
                                           pos_lnum = 36;
                                           pos_bol = 1559;
                                           pos_cnum = 1585
                                         }
                                     })))))) "to_list"
                 [("l = t.contents",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "array.mli";
                          pos_lnum = 36;
                          pos_bol = 1559;
                          pos_cnum = 1571
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "array.mli";
                          pos_lnum = 36;
                          pos_bol = 1559;
                          pos_cnum = 1585
                        }
                    })])
      | (Mem a_3, Res ((Bool, _), b)) ->
          if
            let t_new__040_ = lazy (Model.get (Lazy.force new_state__017_) 0) in
            let t_old__039_ = lazy (Model.get state__015_ 0) in
            (try
               (b = true) =
                 (Ortac_runtime.Gospelstdlib.List.mem a_3
                    (Lazy.force t_new__040_).contents)
             with
             | e ->
                 raise
                   (Ortac_runtime.Partial_function
                      (e,
                        {
                          Ortac_runtime.start =
                            {
                              pos_fname = "array.mli";
                              pos_lnum = 40;
                              pos_bol = 1709;
                              pos_cnum = 1721
                            };
                          Ortac_runtime.stop =
                            {
                              pos_fname = "array.mli";
                              pos_lnum = 40;
                              pos_bol = 1709;
                              pos_cnum = 1746
                            }
                        })))
          then None
          else
            Some
              (Ortac_runtime.report "Array" "make 16 'a'"
                 (Either.right (Res (Ortac_runtime.dummy, ()))) "mem"
                 [("b = List.mem a t.contents",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "array.mli";
                          pos_lnum = 40;
                          pos_bol = 1709;
                          pos_cnum = 1721
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "array.mli";
                          pos_lnum = 40;
                          pos_bol = 1709;
                          pos_cnum = 1746
                        }
                    })])
      | _ -> None
let _ =
  QCheck_base_runner.run_tests_main
    (let count = 1000 in
     [STMTests.agree_test ~count ~name:"Array STM tests" check_init_state
        ortac_postcond])
