(* This file is generated by ortac qcheck-stm,
   edit how you run the tool instead *)
[@@@ocaml.warning "-26-27-69-32"]
open Conjunctive_clauses
module Ortac_runtime = Ortac_runtime_qcheck_stm
let set_contents c i a_1 =
  try
    Ortac_runtime.Gospelstdlib.List.mapi
      (fun j -> fun x -> if i = j then a_1 else x) c
  with
  | e ->
      raise
        (Ortac_runtime.Partial_function
           (e,
             {
               Ortac_runtime.start =
                 {
                   pos_fname = "conjunctive_clauses.mli";
                   pos_lnum = 9;
                   pos_bol = 562;
                   pos_cnum = 572
                 };
               Ortac_runtime.stop =
                 {
                   pos_fname = "conjunctive_clauses.mli";
                   pos_lnum = 9;
                   pos_bol = 562;
                   pos_cnum = 619
                 }
             }))
module SUT =
  (Ortac_runtime.SUT.Make)(struct
                             type sut = char t
                             let init = Some (fun () -> make 42 'a')
                           end)
module ModelElt =
  struct
    type nonrec elt = {
      contents: char list }
    let init =
      Some
        (let i_2 = 42
         and a_3 = 'a' in
         {
           contents =
             (try
                Ortac_runtime.Gospelstdlib.List.init
                  (Ortac_runtime.Gospelstdlib.integer_of_int i_2)
                  (fun _ -> a_3)
              with
              | e ->
                  raise
                    (Ortac_runtime.Partial_function
                       (e,
                         {
                           Ortac_runtime.start =
                             {
                               pos_fname = "conjunctive_clauses.mli";
                               pos_lnum = 6;
                               pos_bol = 277;
                               pos_cnum = 318
                             };
                           Ortac_runtime.stop =
                             {
                               pos_fname = "conjunctive_clauses.mli";
                               pos_lnum = 6;
                               pos_bol = 277;
                               pos_cnum = 342
                             }
                         })))
         })
  end
module Model = (Ortac_runtime.Model.Make)(ModelElt)
module Spec =
  struct
    open STM
    type _ ty +=  
      | Integer: Ortac_runtime.integer ty 
    let integer = (Integer, Ortac_runtime.string_of_integer)
    type sut = SUT.t
    let init_sut = SUT.create
    type state = Model.t
    let init_state = Model.create ()
    type cmd =
      | Set of int * char 
    let show_cmd cmd__001_ =
      match cmd__001_ with
      | Set (i_1, a_2) ->
          Format.asprintf "protect (fun () -> %s sut %a %a)" "set"
            (Util.Pp.pp_int true) i_1 (Util.Pp.pp_char true) a_2
    let cleanup _ = ()
    let arb_cmd _ =
      let open QCheck in
        make ~print:show_cmd
          (let open Gen in
             oneof
               [((pure (fun i_1 -> fun a_2 -> Set (i_1, a_2))) <*> int) <*>
                  char])
    let next_state cmd__002_ state__003_ =
      match cmd__002_ with
      | Set (i_1, a_2) ->
          let tmp__004_ = Model.get state__003_ 0 in
          if
            (try
               let __t1__005_ =
                 Ortac_runtime.Gospelstdlib.(<=)
                   (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                   (Ortac_runtime.Gospelstdlib.integer_of_int i_1) in
               let __t2__006_ =
                 Ortac_runtime.Gospelstdlib.(<)
                   (Ortac_runtime.Gospelstdlib.integer_of_int i_1)
                   (Ortac_runtime.Gospelstdlib.List.length tmp__004_.contents) in
               __t1__005_ && __t2__006_
             with
             | e ->
                 raise
                   (Ortac_runtime.Partial_function
                      (e,
                        {
                          Ortac_runtime.start =
                            {
                              pos_fname = "conjunctive_clauses.mli";
                              pos_lnum = 13;
                              pos_bol = 806;
                              pos_cnum = 817
                            };
                          Ortac_runtime.stop =
                            {
                              pos_fname = "conjunctive_clauses.mli";
                              pos_lnum = 13;
                              pos_bol = 806;
                              pos_cnum = 848
                            }
                        })))
          then
            Model.push (Model.drop_n state__003_ 1)
              {
                contents =
                  (try
                     set_contents tmp__004_.contents
                       (Ortac_runtime.Gospelstdlib.integer_of_int i_1) a_2
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "conjunctive_clauses.mli";
                                    pos_lnum = 15;
                                    pos_bol = 864;
                                    pos_cnum = 905
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "conjunctive_clauses.mli";
                                    pos_lnum = 15;
                                    pos_bol = 864;
                                    pos_cnum = 917
                                  }
                              })))
              }
          else state__003_
    let precond cmd__014_ state__015_ =
      match cmd__014_ with | Set (i_1, a_2) -> true
    let postcond _ _ _ = true
    let run cmd__016_ sut__017_ =
      match cmd__016_ with
      | Set (i_1, a_2) ->
          Res
            ((result unit exn),
              (let tmp__018_ = SUT.pop sut__017_ in
               let res__019_ = protect (fun () -> set tmp__018_ i_1 a_2) () in
               (SUT.push tmp__018_ sut__017_; res__019_)))
  end
module STMTests = (Ortac_runtime.Make)(Spec)
let check_init_state () = ()
let ortac_postcond cmd__007_ state__008_ res__009_ =
  let open Spec in
    let open STM in
      let new_state__010_ = lazy (next_state cmd__007_ state__008_) in
      match (cmd__007_, res__009_) with
      | (Set (i_1, a_2), Res ((Result (Unit, Exn), _), res)) ->
          (match if
                   let tmp__011_ = Model.get state__008_ 0 in
                   try
                     let __t1__012_ =
                       Ortac_runtime.Gospelstdlib.(<=)
                         (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                         (Ortac_runtime.Gospelstdlib.integer_of_int i_1) in
                     let __t2__013_ =
                       Ortac_runtime.Gospelstdlib.(<)
                         (Ortac_runtime.Gospelstdlib.integer_of_int i_1)
                         (Ortac_runtime.Gospelstdlib.List.length
                            tmp__011_.contents) in
                     __t1__012_ && __t2__013_
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "conjunctive_clauses.mli";
                                    pos_lnum = 13;
                                    pos_bol = 806;
                                    pos_cnum = 817
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "conjunctive_clauses.mli";
                                    pos_lnum = 13;
                                    pos_bol = 806;
                                    pos_cnum = 848
                                  }
                              }))
                 then None
                 else
                   Some
                     (Ortac_runtime.report "Conjunctive_clauses"
                        "make 42 'a'" (Either.left "Invalid_argument") "set"
                        [("0 <= i < List.length t.contents",
                           {
                             Ortac_runtime.start =
                               {
                                 pos_fname = "conjunctive_clauses.mli";
                                 pos_lnum = 13;
                                 pos_bol = 806;
                                 pos_cnum = 817
                               };
                             Ortac_runtime.stop =
                               {
                                 pos_fname = "conjunctive_clauses.mli";
                                 pos_lnum = 13;
                                 pos_bol = 806;
                                 pos_cnum = 848
                               }
                           })])
           with
           | None -> (match res with | Ok _ -> None | _ -> None)
           | _ ->
               (match res with
                | Error (Invalid_argument _) -> None
                | _ ->
                    if
                      let tmp__011_ = Model.get state__008_ 0 in
                      (try
                         let __t1__012_ =
                           Ortac_runtime.Gospelstdlib.(<=)
                             (Ortac_runtime.Gospelstdlib.integer_of_int 0)
                             (Ortac_runtime.Gospelstdlib.integer_of_int i_1) in
                         let __t2__013_ =
                           Ortac_runtime.Gospelstdlib.(<)
                             (Ortac_runtime.Gospelstdlib.integer_of_int i_1)
                             (Ortac_runtime.Gospelstdlib.List.length
                                tmp__011_.contents) in
                         __t1__012_ && __t2__013_
                       with
                       | e ->
                           raise
                             (Ortac_runtime.Partial_function
                                (e,
                                  {
                                    Ortac_runtime.start =
                                      {
                                        pos_fname = "conjunctive_clauses.mli";
                                        pos_lnum = 13;
                                        pos_bol = 806;
                                        pos_cnum = 817
                                      };
                                    Ortac_runtime.stop =
                                      {
                                        pos_fname = "conjunctive_clauses.mli";
                                        pos_lnum = 13;
                                        pos_bol = 806;
                                        pos_cnum = 848
                                      }
                                  })))
                    then None
                    else
                      Some
                        (Ortac_runtime.report "Conjunctive_clauses"
                           "make 42 'a'" (Either.left "Invalid_argument")
                           "set"
                           [("0 <= i < List.length t.contents",
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "conjunctive_clauses.mli";
                                    pos_lnum = 13;
                                    pos_bol = 806;
                                    pos_cnum = 817
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "conjunctive_clauses.mli";
                                    pos_lnum = 13;
                                    pos_bol = 806;
                                    pos_cnum = 848
                                  }
                              })])))
      | _ -> None
let _ =
  QCheck_base_runner.run_tests_main
    (let count = 1000 in
     [STMTests.agree_test ~count ~name:"Conjunctive_clauses STM tests"
        check_init_state ortac_postcond])
