(* This file is generated by ortac qcheck-stm,
   edit how you run the tool instead *)
[@@@ocaml.warning "-26-27-69-32"]
open Functional_model
module Ortac_runtime = Ortac_runtime_qcheck_stm
module SUT =
  (Ortac_runtime.SUT.Make)(struct
                             type sut = (char, int) t
                             let init = Some (fun () -> empty ())
                           end)
module ModelElt =
  struct
    type nonrec elt = {
      m: char -> int option }
    let init =
      Some
        (let () = () in
         {
           m =
             (try fun _ -> None
              with
              | e ->
                  raise
                    (Ortac_runtime.Partial_function
                       (e,
                         {
                           Ortac_runtime.start =
                             {
                               pos_fname = "functional_model.mli";
                               pos_lnum = 6;
                               pos_bol = 275;
                               pos_cnum = 293
                             };
                           Ortac_runtime.stop =
                             {
                               pos_fname = "functional_model.mli";
                               pos_lnum = 6;
                               pos_bol = 275;
                               pos_cnum = 306
                             }
                         })))
         })
  end
module Model = (Ortac_runtime.Model.Make)(ModelElt)
module Spec =
  struct
    open STM
    type _ ty +=  
      | Integer: Ortac_runtime.integer ty 
    let integer = (Integer, Ortac_runtime.string_of_integer)
    type sut = SUT.t
    let init_sut = SUT.create
    type state = Model.t
    let init_state = Model.create ()
    type cmd =
      | Add of char * int 
    let show_cmd cmd__001_ =
      match cmd__001_ with
      | Add (a_1, b_1) ->
          Format.asprintf "%s sut %a %a" "add" (Util.Pp.pp_char true) a_1
            (Util.Pp.pp_int true) b_1
    let cleanup _ = ()
    let arb_cmd _ =
      let open QCheck in
        make ~print:show_cmd
          (let open Gen in
             oneof
               [((pure (fun a_1 -> fun b_1 -> Add (a_1, b_1))) <*> char) <*>
                  int])
    let next_state cmd__002_ state__003_ =
      match cmd__002_ with
      | Add (a_1, b_1) ->
          let tmp__004_ = Model.get state__003_ 0 in
          Model.push (Model.drop_n state__003_ 1)
            {
              m =
                (try fun x -> if x = a_1 then Some b_1 else tmp__004_.m x
                 with
                 | e ->
                     raise
                       (Ortac_runtime.Partial_function
                          (e,
                            {
                              Ortac_runtime.start =
                                {
                                  pos_fname = "functional_model.mli";
                                  pos_lnum = 11;
                                  pos_bol = 482;
                                  pos_cnum = 500
                                };
                              Ortac_runtime.stop =
                                {
                                  pos_fname = "functional_model.mli";
                                  pos_lnum = 11;
                                  pos_bol = 482;
                                  pos_cnum = 546
                                }
                            })))
            }
    let precond cmd__010_ state__011_ =
      match cmd__010_ with | Add (a_1, b_1) -> true
    let postcond _ _ _ = true
    let run cmd__012_ sut__013_ =
      match cmd__012_ with
      | Add (a_1, b_1) ->
          Res
            (unit,
              (let tmp__014_ = SUT.pop sut__013_ in
               let res__015_ = add tmp__014_ a_1 b_1 in
               (SUT.push tmp__014_ sut__013_; res__015_)))
  end
module STMTests = (Ortac_runtime.Make)(Spec)
let check_init_state () = ()
let ortac_postcond cmd__005_ state__006_ res__007_ =
  let open Spec in
    let open STM in
      let new_state__008_ = lazy (next_state cmd__005_ state__006_) in
      match (cmd__005_, res__007_) with
      | (Add (a_1, b_1), Res ((Unit, _), _)) -> None
      | _ -> None
let _ =
  QCheck_base_runner.run_tests_main
    (let count = 1000 in
     [STMTests.agree_test ~count ~name:"Functional_model STM tests"
        check_init_state ortac_postcond])
